RockyInternetShop/Controllers/CartController.cs
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using RockyDataAccess.Reporitory.AppUserDomain;
using RockyDataAccess.Reporitory.InquiryDomain;
using RockyDataAccess.Reporitory.OrderDomain;
using RockyDataAccess.Reporitory.ProductDomain;
using RockyModels;
using RockyModels.InquiryDomain;
using RockyModels.OrderDomain;
using RockyModels.ViewModel;
using RockyUtility;
using RockyUtility.BrainTreeDomain;
using System.Security.Claims;
using System.Text;

namespace RockyInternetShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnv;
        private readonly IEmailSender _emailSender;
        private readonly IProductRepository _prodRep;
        private readonly IAppUserRepository _userRep;
        private readonly IInquiryHeaderRepository _inqHdrRep;
        private readonly IInquiryDetailRepository _inqDtlRep;
        private readonly IOrderHeaderRepository _ordHdrRep;
        private readonly IOrderDetailRepository _ordDtlRep;
        private readonly IBrainTreeGate _gate;

        [BindProperty]
        public ProductUserVM ProdUserVm { get; set; }

        public CartController(IWebHostEnvironment webHostEnv,
                                IEmailSender emailSender,
                                IProductRepository prodRep,
                                 IAppUserRepository userRep,
                                 IInquiryHeaderRepository inqHdrRep,
                                 IInquiryDetailRepository inqDtlRep,
                                 IOrderHeaderRepository ordHdrRep,
                                 IOrderDetailRepository ordDtlRep,
                                 IBrainTreeGate gate)
        {
            _webHostEnv = webHostEnv;
            _emailSender = emailSender;
            _prodRep = prodRep;
            _userRep = userRep;
            _inqHdrRep = inqHdrRep;
            _inqDtlRep = inqDtlRep;
            _ordHdrRep = ordHdrRep;
            _ordDtlRep = ordDtlRep;
            _gate = gate;
        }

        public IActionResult Index()
        {
            var shpCarts = new List<ShoppingCart>();

            if (HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart) != null &&
                HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart).Any())
            {
                shpCarts = HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart);
            }
            var prodId = shpCarts.Select(z => z.ProductId);
            var products = _prodRep.GetAll(filter: z => prodId.Contains(z.Id)).ToList();

            foreach (var cart in shpCarts)
            {
                products.FirstOrDefault(x => x.Id == cart.ProductId).QuantityTemp = (int)cart.QuantityTemp;
            }

            return View(products);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Product> products)
        {
            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
            foreach (var product in products)
            {
                shoppingCarts.Add(new ShoppingCart { ProductId = product.Id, QuantityTemp = product.QuantityTemp });
            }
            HttpContext.Session.Set<List<ShoppingCart>>(WebConstant.SessionCart, shoppingCarts);

            return RedirectToAction(nameof(Summary));
        }

        public IActionResult Summary()
        {
            AppUser appUser = new AppUser();

            if (User.IsInRole(WebConstant.AdminRole))
            {
                if (HttpContext.Session.Get(WebConstant.SessionInquiryId) != null)
                {
                    var head = _inqHdrRep.FirstOrDefault(filter: x => x.Id == HttpContext.Session.Get<long>(WebConstant.SessionInquiryId));
                    if (head != null)
                    {
                        appUser = new AppUser
                        {
                            Email = head.Email,
                            FullName = head.FullName,
                            PhoneNumber = head.Phone
                        };
                    }
                }
                else
                {
                    appUser = new AppUser();
                }

                var gate = _gate.GetGateWay();
                var token = gate.ClientToken.Generate();
                ViewBag.ClientToken = token;

            }
            else
            {
                //var UserId = User.FindFirstValue(ClaimTypes.Name);
                var claimsIdentity = User.Identity as ClaimsIdentity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                appUser = _userRep.FirstOrDefault(x => x.Id == claim.Value);
            }

            var shpCarts = new List<ShoppingCart>();

            if (HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart) != null &&
                HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart).Any())
            {
                shpCarts = HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart);
            }
            var prodId = shpCarts.Select(z => z.ProductId);
            var products = _prodRep.GetAll(filter: z => prodId.Contains(z.Id)).ToList();
            foreach (var product in products)
            {
                product.QuantityTemp = shpCarts.FirstOrDefault(z => z.ProductId == product.Id).QuantityTemp;
            }

            ProdUserVm = new ProductUserVM
            {
                AppUser = appUser,
                Products = products
            };

            return View(ProdUserVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPostAsync(IFormCollection collection, ProductUserVM ProdUserVm)
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (User.IsInRole(WebConstant.AdminRole))
            {
                //order
                return Order(ProdUserVm, claim, collection);
            }
            else
            {
                //inquiry
                return await Inquiry(ProdUserVm, claim);
            }
        }

        private IActionResult Order(ProductUserVM ProdUserVm, Claim? claim, IFormCollection collection)
        {
            var orderTotal = 0.0;
            orderTotal = ProdUserVm.Products.Sum(x => x.QuantityTemp * x.Price);

            var orderHeader = new OrderHeader()
            {
                CreatedByUserId = claim.Value,
                FinalOrderTotal = orderTotal,
                City = ProdUserVm.AppUser.City,
                State = ProdUserVm.AppUser.State,
                Email = ProdUserVm.AppUser.Email,
                PhoneNumber = ProdUserVm.AppUser.PhoneNumber,
                PostalCode = ProdUserVm.AppUser.PostalCode,
                StreetAddress = ProdUserVm.AppUser.StreetAddress,
                FullName = ProdUserVm.AppUser.FullName,
                OrderDate = DateTime.Now,
                OrderStatus = WebConstant.StatusPending
            };

            _ordHdrRep.Add(orderHeader);
            _ordHdrRep.SaveChanges();

            foreach (var prod in ProdUserVm.Products)
            {
                var det = new OrderDetail
                {
                    OrderHeaderId = orderHeader.Id,
                    ProductId = prod.Id,
                    PricePerQuant = prod.Price,
                    Quant = prod.QuantityTemp
                };

                _ordDtlRep.Add(det);
            }
            _ordDtlRep.SaveChanges();

            string nonceFromTheClient = collection["payment_method_nonce"];
            var request = new TransactionRequest
            {
                Amount = (decimal)orderTotal,
                PaymentMethodNonce = nonceFromTheClient,
                OrderId = orderHeader.Id.ToString(),
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };
            var gateWay = _gate.GetGateWay();
            var result = gateWay.Transaction.Sale(request);
            if (result.Target.ProcessorResponseText == "Approved")
            {
                orderHeader.TransactionId = result.Target.Id;
                orderHeader.OrderStatus = WebConstant.StatusApproved;
            }
            else
            {
                orderHeader.OrderStatus = WebConstant.StatusCancelled;
            }
            _ordHdrRep.SaveChanges();

            return RedirectToAction(nameof(InquiryConfirmation), new { id = orderHeader.Id });
        }

        private async Task<IActionResult> Inquiry(ProductUserVM ProdUserVm, Claim? claim)
        {
            var PathToTemplate = _webHostEnv.WebRootPath + Path.DirectorySeparatorChar.ToString() + "templates" + Path.DirectorySeparatorChar.ToString() + "Inquiry.html";
            var Subject = "New Inquiry";
            string HtmlBody = string.Empty;
            using (StreamReader sr = System.IO.File.OpenText(PathToTemplate))
            {
                HtmlBody = sr.ReadToEnd();
            }

            StringBuilder stringBuilder = new StringBuilder();
            foreach (var prod in ProdUserVm.Products)
            {
                stringBuilder.Append($" - Name: {prod.Name} <span style='font-size:14px;'> (ID: {prod.Id})</span><br></br>");
            }

            string messageBody = string.Format(HtmlBody,
                                                ProdUserVm.AppUser.FullName,
                                                ProdUserVm.AppUser.Email,
                                                ProdUserVm.AppUser.PhoneNumber,

RockyInternetShop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockyDataAccess.Reporitory.CategoryDomain;
using RockyModels;
using RockyUtility;

namespace RockyInternetShop.Controllers
{
    [Authorize(Roles = WebConstant.AdminRole)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _rep;

        public CategoryController(ICategoryRepository rep)
        {
            _rep = rep;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _rep.GetAll();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _rep.Add(category);
                _rep.SaveChanges();

                TempData[WebConstant.Success] = "Added successfully";

                return RedirectToAction("Index");
            }
            TempData[WebConstant.Error] = "Added error";

            return View(category);
        }

        public IActionResult Edit(long? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var category = _rep.Find((long)id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _rep.Update(category);
                _rep.SaveChanges();

                TempData[WebConstant.Success] = "Edited successfully";

                return RedirectToAction("Index");
            }
            TempData[WebConstant.Error] = "Edited error";

            return View(category);
        }

        public IActionResult Delete(long? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var category = _rep.Find((long)id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(long? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var category = _rep.Find((long)id);
            if (category == null)
            {
                return NotFound();
            }

            _rep.Remove(category);
            _rep.SaveChanges();

            TempData[WebConstant.Success] = "Deleted successfully";

            return RedirectToAction("Index");
        }
    }
}

RockyInternetShop/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockyDataAccess.Reporitory.InquiryDomain;
using RockyModels;
using RockyModels.ViewModel;
using RockyUtility;

namespace RockyInternetShop.Controllers
{
    [Authorize(Roles = WebConstant.AdminRole)]
    public class InquiryController : Controller
    {
        private readonly IInquiryHeaderRepository _headerRepository;
        private readonly IInquiryDetailRepository _detailRepository;
        [BindProperty]
        public InquiryVM InqVM { get; set; }

        public InquiryController(IInquiryHeaderRepository headerRepository, IInquiryDetailRepository detailRepository)
        {
            _detailRepository = detailRepository;
            _headerRepository = headerRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details()
        {
            var carts = new List<ShoppingCart>();

            InqVM.Details = _detailRepository.GetAll(x => x.InquiryHeaderId == InqVM.Header.Id);
            foreach (var detail in InqVM.Details)
            {
                var cart = new ShoppingCart() { ProductId = detail.ProductId };
                carts.Add(cart);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WebConstant.SessionCart, carts);
            HttpContext.Session.Set(WebConstant.SessionInquiryId, InqVM.Header.Id);

            return RedirectToAction("Index", "Cart");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete()
        {
            _headerRepository.RemoveWithDeatails(InqVM.Header, _detailRepository);
            _headerRepository.SaveChanges();

            TempData[WebConstant.Success] = "Deleted successfully";

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(long id)
        {
            InqVM = new InquiryVM
            {
                Header = _headerRepository.FirstOrDefault(x => x.Id == id),
                Details = _detailRepository.GetAll(x => x.InquiryHeaderId == id, includedProperties: "Product")
            };

            return View(InqVM);
        }

        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new { data = _headerRepository.GetAll() });
        }
    }
}

RockyInternetShop/Views/Shared/_ItemProductCard.cshtml
@using RockyUtility;
@model Product
<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}",Model.Price)</span></label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3 w-100" style="height:300px;" src="@WebConstant.ImgPath@Model.ImageUrl" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush;">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue;">@Model.AppType.Name</span>
            </div>
            <div class="col-12 p-1">
                <a asp-controller="Home" asp-action="Details" asp-route-Id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

RockyInternetShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using RockyUtility;
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RockyInternetShop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link href="~/FontAwesome/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RockyInternetShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/images/tile.png" width="40%" />
                            </a>
                        </li>

                        @if (User.IsInRole(WebConstant.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content managment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">AppType</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create Admin user</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order/Inquiry managment
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                                </div>
                            </li>
                        }

                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart) != null)
                            {
                                <a asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WebConstant.SessionCart).Count;
                                    }
                                    <i class="fas fa-shopping-cart"></i>&nbsp; (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            }
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"></partial>
            </div>
        </nav>
    </header>
    <div class="container mb-4 pb-4">
        <main role="main" class="pb-3">
            <partial name="_Notifications"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container text-white-50">
            &copy; 2023 - RockyInternetShop
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <ejs-scripts></ejs-scripts>
</body>
</html>

RockyInternetShop/Views/Shared/_Notifications.cshtml
@using RockyUtility;


@if (TempData[WebConstant.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.success('@TempData[WebConstant.Success]');
    </script>
}
@if (TempData[WebConstant.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.error('@TempData[WebConstant.Error]');
    </script>
}